export const fakeTeams = [
  {
    name: "Space Invaders",
    admin: "Eshita Das",
    members: ["Shreya Roy", "Riya Das", "Eshita Das", "Tanaya Ghosh"],
    skills: [
      "React.js",
      "Next.js",
      "C",
      "php",
      "mySql",
      "AWS",
      "Figma",
      "Docker",
      "Kubernetes",
      "AI/ML",
    ],
    desc: "lorem ipsum dolor sit. temae ameka dolor dolor lorem ipsum dolor sit.",
    githubLink: "https://github.com/Edasgh",
    email: "testemail1@mail.com",
  },

  {
    name: "Nervewreckers",
    admin: "Eshita Das",
    members: ["Shreya Roy", "Riya Das", "Eshita Das", "Tanaya Ghosh"],
    skills: [
      "React.js",
      "Next.js",
      "C",
      "php",
      "mySql",
      "AWS",
      "Figma",
      "Docker",
      "Kubernetes",
      "AI/ML",
    ],
    desc: "lorem ipsum dolor sit. temae ameka dolor dolor lorem ipsum dolor sit.lorem ipsum dolor sit. temae a",
    githubLink: "https://github.com/Edasgh",
    email: "testemail2@mail.com",
  },
  {
    name: "Test Team",
    admin: "Shreya Roy",
    members: [
      "Shreya Roy",
      "Riya Das",
      "Eshita Das",
      "Priya Roy",
      "Sagnika Goswami",
      "Tanaya Ghosh",
    ],
    skills: ["React.js", "Next.js", "C", "php", "mySql", "AWS", "Figma"],
    desc: "lorem ipsum dolor sit. temae ameka dolor dolor lorem ipsum dolor sit.",
    githubLink: "https://github.com/Edasgh",
    email: "testemail3@mail.com",
  },
];

export const fakeTeamMates = [
  {
    name: "Eshita Das",
    email: "testemail1@mail.com",
    country: "IN",
    githubID: "Edasgh",
    bio: "lorem ipsum dolor sit. temae ameka dolor dolor lorem ipsum dolor sit.lorem ipsum dolor sit. temae a",
    skills: [
      "React.js",
      "Next.js",
      "C",
      "php",
      "mySql",
      "AWS",
      "Figma",
      "Docker",
      "Kubernetes",
      "AI/ML",
    ],
  },
  {
    name: "Ritu Das",
    email: "testemail5@mail.com",
    country: "IN",
    githubID: "testUser",
    bio: "lorem ipsum dolor sit. temae ameka dolor dolor lorem ipsum dolor sit.",
    skills: ["React.js", "Next.js", "C", "php", "mySql", "AWS"],
  },
  {
    name: "Priyanka Khan",
    email: "testemail7@mail.com",
    country: "US",
    githubID: "testUser",
    bio: "lorem ipsum dolor sit. temae ameka dolor dolor lorem ipsum dolor sit.",
    skills: ["React.js", "Next.js", "C", "php", "mySql", "AWS"],
  },
];
